import type { Metadata } from 'next'
import { Red_Hat_Mono } from 'next/font/google'
import './globals.css'

const redHatMono = Red_Hat_Mono({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <div className='container-fluid h-bg-primary'>
        <body className={`${redHatMono.className} h-secondary`}>{children}</body>
      </div>
    </html>
  )
}
